Update patch set 1
Patch Set 1:

Hey, this fixed the missing support library errors but now I have a new error

vendor/cmsdk/sdk/src/java/cyanogenmod/preference/SelfRemovingListPreference.java:37: error: cannot find symbol
                R.styleable.cm_ListPreference, 0, 0);
                 ^
  symbol:   variable styleable
  location: class R
vendor/cmsdk/sdk/src/java/cyanogenmod/preference/SelfRemovingListPreference.java:40: error: cannot find symbol
            mAutoSummary = a.getBoolean(R.styleable.cm_ListPreference_autoSummary, false);
                                         ^
  symbol:   variable styleable
  location: class R
vendor/cmsdk/sdk/src/java/cyanogenmod/preference/Constraints.java:45: error: cannot find symbol
                R.styleable.cm_SelfRemovingPreference, 0, 0);
                 ^
  symbol:   variable styleable
  location: class R
vendor/cmsdk/sdk/src/java/cyanogenmod/preference/Constraints.java:50: error: cannot find symbol
            String rPackage = a.getString(R.styleable.cm_SelfRemovingPreference_requiresPackage);
                                           ^
  symbol:   variable styleable
  location: class R
vendor/cmsdk/sdk/src/java/cyanogenmod/preference/Constraints.java:56: error: cannot find symbol
            String rFeature = a.getString(R.styleable.cm_SelfRemovingPreference_requiresFeature);
                                           ^
  symbol:   variable styleable
  location: class R
vendor/cmsdk/sdk/src/java/cyanogenmod/preference/Constraints.java:62: error: cannot find symbol
            String rProperty = a.getString(R.styleable.cm_SelfRemovingPreference_requiresProperty);
                                            ^
  symbol:   variable styleable
  location: class R
vendor/cmsdk/sdk/src/java/cyanogenmod/preference/Constraints.java:72: error: cannot find symbol
           TypedValue tv = a.peekValue(R.styleable.cm_SelfRemovingPreference_requiresConfig);
                                        ^
  symbol:   variable styleable
  location: class R
Note: vendor/cmsdk/sdk/src/java/cyanogenmod/profiles/ConnectionSettings.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
7 errors
build/core/java.mk:448: recipe for target '/media/sooti/new_big/aosp/out/target/common/obj/JAVA_LIBRARIES/org.cyanogenmod.platform.sdk_intermediates/classes-full-debug.jar' failed
make: *** [/media/sooti/new_big/aosp/out/target/common/obj/JAVA_LIBRARIES/org.cyanogenmod.platform.sdk_intermediates/classes-full-debug.jar] Error 41
make: *** Waiting for unfinished jobs....
vendor/cmsdk/sdk/src/java/cyanogenmod/preference/SelfRemovingListPreference.java:37: error: cannot find symbol
                R.styleable.cm_ListPreference, 0, 0);
                 ^
  symbol:   variable styleable
  location: class R
vendor/cmsdk/sdk/src/java/cyanogenmod/preference/SelfRemovingListPreference.java:40: error: cannot find symbol
            mAutoSummary = a.getBoolean(R.styleable.cm_ListPreference_autoSummary, false);
                                         ^
  symbol:   variable styleable
  location: class R
vendor/cmsdk/sdk/src/java/cyanogenmod/preference/Constraints.java:45: error: cannot find symbol
                R.styleable.cm_SelfRemovingPreference, 0, 0);
                 ^
  symbol:   variable styleable
  location: class R
vendor/cmsdk/sdk/src/java/cyanogenmod/preference/Constraints.java:50: error: cannot find symbol
            String rPackage = a.getString(R.styleable.cm_SelfRemovingPreference_requiresPackage);
                                           ^
  symbol:   variable styleable
  location: class R
vendor/cmsdk/sdk/src/java/cyanogenmod/preference/Constraints.java:56: error: cannot find symbol
            String rFeature = a.getString(R.styleable.cm_SelfRemovingPreference_requiresFeature);
                                           ^
  symbol:   variable styleable
  location: class R
vendor/cmsdk/sdk/src/java/cyanogenmod/preference/Constraints.java:62: error: cannot find symbol
            String rProperty = a.getString(R.styleable.cm_SelfRemovingPreference_requiresProperty);
                                            ^
  symbol:   variable styleable
  location: class R
vendor/cmsdk/sdk/src/java/cyanogenmod/preference/Constraints.java:72: error: cannot find symbol
           TypedValue tv = a.peekValue(R.styleable.cm_SelfRemovingPreference_requiresConfig);
                                        ^
  symbol:   variable styleable
  location: class R

Patch-set: 1