Update patch set 5
Patch Set 5:

ERROR: /home/lord/source/AICP_MM/frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/LiveLockScreenController.java:126: The type new KeyguardExternalView.KeyguardExternalViewCallbacks(){} must implement the inherited abstract method KeyguardExternalView.KeyguardExternalViewCallbacks.slideLockscreenIn()


slideLockscreenIn needs to be overriden in LiveLockScreenController

I've fixed it locally by only overriding the method and not including anything in.. I don't know for sure if that is good way, so won't push anything

Patch-set: 5
Reviewer: LorD ClockaN <1458@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0